#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu -i -m 0 -b -fn "Gohu GohuFont:pixelsize=11" -nb "#222222" -nf "#bbbbbb" -sb "#bbbbbb" -sf "#222222" "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass show "$password" | xclip
else
	xdotool - <<<"type --clearmodifiers -- $(pass show "$password" | head -n 1)"
fi
